from django.db import migrations, models
import django.db.models.deletion
import uuid

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name='Project', fields=[('id', models.CharField(max_length=32, primary_key=True, serialize=False)),('prompt',models.TextField(blank=True)),('category',models.CharField(choices=[('equipment','equipment'),('module','module'),('part','part')],default='equipment',max_length=16)),('status',models.CharField(default='created',max_length=40)),('progress',models.PositiveSmallIntegerField(default=0)),('step',models.CharField(default='input',max_length=16)),('selected_2d_id',models.CharField(blank=True,max_length=80,null=True)),('revision',models.PositiveIntegerField(default=1)),('analysis',models.JSONField(blank=True,null=True)),('pipeline',models.JSONField(blank=True,null=True)),('result_3d',models.JSONField(blank=True,null=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True))]),
        migrations.CreateModel(name='Asset', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('kind',models.CharField(max_length=40)),('original_name',models.CharField(blank=True,max_length=255)),('relative_path',models.CharField(max_length=1000)),('public_url',models.CharField(max_length=1000)),('metadata',models.JSONField(blank=True,default=dict)),('created_at',models.DateTimeField(auto_now_add=True)),('project',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='assets',to='api.project'))]),
        migrations.CreateModel(name='Concept2D', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('concept_id',models.CharField(max_length=80)),('title',models.CharField(blank=True,max_length=255)),('description',models.TextField(blank=True)),('public_url',models.CharField(max_length=1000)),('relative_path',models.CharField(max_length=1000)),('metadata',models.JSONField(blank=True,default=dict)),('project',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='concepts',to='api.project'))], options={'unique_together':{('project','concept_id')}}),
        migrations.CreateModel(name='MeetingSession', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('status',models.CharField(default='idle',max_length=40)),('transcript',models.TextField(blank=True)),('analysis',models.JSONField(blank=True,null=True)),('chunk_count',models.PositiveIntegerField(default=0)),('provider',models.CharField(blank=True,max_length=120)),('updated_at',models.DateTimeField(auto_now=True)),('project',models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,related_name='meeting',to='api.project'))]),
        migrations.CreateModel(name='GenerationJob', fields=[('id',models.UUIDField(default=uuid.uuid4,editable=False,primary_key=True,serialize=False)),('job_type',models.CharField(max_length=40)),('status',models.CharField(choices=[('queued','queued'),('running','running'),('completed','completed'),('failed','failed')],default='queued',max_length=16)),('progress',models.PositiveSmallIntegerField(default=0)),('payload',models.JSONField(blank=True,default=dict)),('result',models.JSONField(blank=True,null=True)),('error',models.TextField(blank=True)),('created_at',models.DateTimeField(auto_now_add=True)),('updated_at',models.DateTimeField(auto_now=True)),('project',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='jobs',to='api.project'))]),
        migrations.CreateModel(name='TranscriptSegment', fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('chunk_index',models.PositiveIntegerField(default=0)),('start',models.FloatField(default=0)),('end',models.FloatField(default=0)),('speaker',models.CharField(default='SPEAKER_00',max_length=80)),('text',models.TextField()),('confidence',models.FloatField(default=0)),('created_at',models.DateTimeField(auto_now_add=True)),('meeting',models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name='segments',to='api.meetingsession'))]),
    ]
