from __future__ import annotations

import json
import os
from pathlib import Path

import carb
import omni.ext
import omni.kit.app
import omni.ui as ui
import omni.usd
from pxr import Sdf, Usd


class XconcepMeetingReviewExtension(omni.ext.IExt):
    """Kit extension for layered OpenUSD review generated by the PHP/Python platform."""

    def on_startup(self, ext_id: str):
        self._ext_id = ext_id
        self._manifest_mtime = 0.0
        self._manifest_path = ""
        self._window = ui.Window("X concep Meeting Review", width=420, height=620)
        self._status = None
        self._revision = None
        self._summary = None
        self._variant = None
        self._build_ui()
        stream = omni.kit.app.get_app().get_update_event_stream()
        self._subscription = stream.create_subscription_to_pop(self._on_update, name="xconcep_manifest_watch")
        settings = carb.settings.get_settings()
        configured = settings.get_as_string("exts/xconcep.meeting.review/manifestPath")
        if configured:
            self._set_manifest(configured)

    def on_shutdown(self):
        self._subscription = None
        self._window = None

    def _build_ui(self):
        with self._window.frame:
            with ui.VStack(spacing=10, height=0):
                ui.Label("Meeting-driven OpenUSD Review", style={"font_size": 20})
                ui.Label("Layered USD · Variants · PhysX · Nucleus · WebRTC", style={"color": 0xFF76D7E8})
                self._manifest_model = ui.SimpleStringModel("")
                ui.StringField(self._manifest_model, height=28)
                with ui.HStack(height=34, spacing=8):
                    ui.Button("Manifest 열기", clicked_fn=self._open_from_field)
                    ui.Button("Stage 새로고침", clicked_fn=self._reload)
                self._status = ui.Label("Manifest 대기", word_wrap=True)
                ui.Separator()
                self._revision = ui.Label("Revision: -")
                self._summary = ui.Label("회의 요약: -", word_wrap=True)
                ui.Separator()
                ui.Label("Design Variant")
                with ui.HStack(height=32, spacing=8):
                    ui.Button("Selected", clicked_fn=lambda: self._apply_variant("Selected"))
                    ui.Button("Meeting Revision", clicked_fn=lambda: self._apply_variant("MeetingRevision"))
                ui.Button("OpenUSD Asset 검증", height=32, clicked_fn=self._validate_current_stage)
                ui.Button("Nucleus 게시 스크립트 안내", height=32, clicked_fn=self._show_nucleus_hint)
                ui.Spacer()
                ui.Label("브라우저 스트리밍은 omni.kit.livestream.app + Web SDK로 제공함", word_wrap=True)

    def _open_from_field(self):
        self._set_manifest(self._manifest_model.get_value_as_string())

    def _set_manifest(self, value: str):
        value = value.strip()
        if not value:
            return
        self._manifest_path = value
        self._manifest_model.set_value(value)
        self._load_manifest(force=True)

    def _on_update(self, _event):
        if not self._manifest_path:
            return
        try:
            mtime = os.path.getmtime(self._manifest_path)
        except OSError:
            return
        if mtime > self._manifest_mtime:
            self._load_manifest(force=True)

    def _load_manifest(self, force: bool = False):
        try:
            path = Path(self._manifest_path)
            payload = json.loads(path.read_text(encoding="utf-8"))
            root = path.parent / payload.get("default_stage", "root.usda")
            self._manifest_mtime = path.stat().st_mtime
            omni.usd.get_context().open_stage(str(root))
            self._revision.text = f"Revision: {payload.get('revision', '-')}"
            meeting = payload.get("meeting_analysis") or {}
            self._summary.text = f"회의 요약: {meeting.get('summary', '-')}"
            self._status.text = f"Stage 열림: {root}"
        except Exception as exc:
            carb.log_error(f"X concep manifest load failed: {exc}")
            if self._status:
                self._status.text = f"오류: {exc}"

    def _reload(self):
        self._load_manifest(force=True)

    def _apply_variant(self, variant_name: str):
        stage = omni.usd.get_context().get_stage()
        if not stage:
            self._status.text = "열린 Stage가 없음"
            return
        asset = stage.GetPrimAtPath("/World/Asset")
        if not asset:
            self._status.text = "/World/Asset Prim이 없음"
            return
        variant_set = asset.GetVariantSets().GetVariantSet("designOption")
        if variant_set:
            variant_set.SetVariantSelection(variant_name)
            stage.GetRootLayer().Save()
            self._status.text = f"Variant 적용: {variant_name}"
        else:
            self._status.text = "designOption VariantSet이 없음"

    def _validate_current_stage(self):
        try:
            import omni.asset_validator.core
            stage = omni.usd.get_context().get_stage()
            if not stage:
                self._status.text = "열린 Stage가 없음"
                return
            engine = omni.asset_validator.core.ValidationEngine()
            results = engine.validate(stage)
            issue_count = len(getattr(results, "issues", []) or [])
            self._status.text = f"Asset Validator 완료 · 이슈 {issue_count}건"
        except Exception as exc:
            self._status.text = f"검증 실패: {exc}"

    def _show_nucleus_hint(self):
        self._status.text = "omniverse-kit/scripts/publish_nucleus.py를 Kit Python에서 실행함"
