from __future__ import annotations

"""Safe raw-image/JSONL preprocessing for the Xconcep CAD-VLM dataset.

Raw JSONL records need ``id``, ``category``, ``prompt``, ``images`` and
``provenance``.  ``images`` may be strings or ``{"path", "view"}`` objects.
``split``, ``source_analysis``, ``design_spec`` and ``geometry_contract`` are
optional.  Missing DesignSpec/GeometryContract values are deterministically
generated by the current Xconcep parametric generators.
"""

import hashlib
import json
import re
import shutil
import uuid
from collections import defaultdict
from pathlib import Path
from typing import Any

from PIL import Image, ImageOps

from .dataset import (
    CATEGORIES,
    DATASET_SCHEMA,
    MODE_FOR_CATEGORY,
    SPLITS,
    DatasetValidationError,
    validate_dataset,
)


PACKAGE_ROOT = Path(__file__).resolve().parents[2]
STACK_ROOT = PACKAGE_ROOT.parents[1]


def _sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def _sha256_text(value: str) -> str:
    return _sha256_bytes(value.encode("utf-8"))


def _safe_relative_path(root: Path, value: str) -> Path:
    path = (root / value).resolve()
    try:
        path.relative_to(root)
    except ValueError as exc:
        raise DatasetValidationError(f"input image path escapes manifest directory: {value}") from exc
    if not path.is_file():
        raise DatasetValidationError(f"input image not found: {value}")
    return path


def _slug(value: str, fallback: str) -> str:
    token = re.sub(r"[^A-Za-z0-9가-힣._-]+", "_", value).strip("._")
    return token[:96] or fallback


def _read_jsonl(path: Path) -> list[dict[str, Any]]:
    if not path.is_file():
        raise DatasetValidationError(f"raw manifest not found: {path}")
    records: list[dict[str, Any]] = []
    for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        if not line.strip():
            continue
        try:
            value = json.loads(line)
        except json.JSONDecodeError as exc:
            raise DatasetValidationError(f"invalid raw JSON at {path.name}:{line_number}: {exc}") from exc
        if not isinstance(value, dict):
            raise DatasetValidationError(f"raw record at line {line_number} must be an object")
        value["_line_number"] = line_number
        records.append(value)
    if not records:
        raise DatasetValidationError("raw manifest contains no records")
    return records


def _read_allowlist(path: Path | None) -> tuple[set[str], Path]:
    selected = path or (PACKAGE_ROOT / "schema" / "license_allowlist.json")
    if not selected.is_file():
        raise DatasetValidationError(f"license allowlist not found: {selected}")
    value = json.loads(selected.read_text(encoding="utf-8"))
    allowed = {str(item) for item in value.get("allowed_training_licenses", [])}
    if not allowed:
        raise DatasetValidationError("license allowlist is empty")
    return allowed, selected


def _image_entries(raw: dict[str, Any], root: Path, minimum: int) -> list[dict[str, Any]]:
    images = raw.get("images")
    if not isinstance(images, list) or len(images) < minimum:
        raise DatasetValidationError(f"line {raw['_line_number']}: images must contain at least {minimum} item(s)")
    result: list[dict[str, Any]] = []
    for index, item in enumerate(images):
        if isinstance(item, str):
            relative, view = item, Path(item).stem.rsplit("_", 1)[-1]
        elif isinstance(item, dict):
            relative = str(item.get("path") or item.get("image") or "")
            view = str(item.get("view") or Path(relative).stem.rsplit("_", 1)[-1])
        else:
            raise DatasetValidationError(f"line {raw['_line_number']}: image entry {index} is invalid")
        if not relative:
            raise DatasetValidationError(f"line {raw['_line_number']}: image entry {index} has no path")
        source = _safe_relative_path(root, relative)
        result.append({"source": source, "view": _slug(view, f"view_{index + 1:02d}"), "digest": _sha256_bytes(source.read_bytes())})
    return result


class _UnionFind:
    def __init__(self, count: int):
        self.parent = list(range(count))

    def find(self, value: int) -> int:
        while self.parent[value] != value:
            self.parent[value] = self.parent[self.parent[value]]
            value = self.parent[value]
        return value

    def union(self, left: int, right: int) -> None:
        left, right = self.find(left), self.find(right)
        if left != right:
            self.parent[right] = left


def _assign_splits(rows: list[dict[str, Any]], ratios: tuple[float, float, float]) -> None:
    if len(ratios) != 3 or any(value < 0 for value in ratios) or abs(sum(ratios) - 1.0) > 1e-6:
        raise DatasetValidationError("split ratios must be three non-negative values summing to 1.0")
    union = _UnionFind(len(rows))
    seen: dict[str, int] = {}
    for index, row in enumerate(rows):
        keys = [row["prompt_hash"], *[item["digest"] for item in row["image_entries"]]]
        for key in keys:
            if key in seen:
                union.union(index, seen[key])
            else:
                seen[key] = index
    groups: dict[int, list[int]] = defaultdict(list)
    for index in range(len(rows)):
        groups[union.find(index)].append(index)
    labels = ("train", "eval", "test")
    for indexes in groups.values():
        explicit = {str(rows[index].get("split") or "") for index in indexes if rows[index].get("split")}
        if any(value not in SPLITS for value in explicit):
            raise DatasetValidationError(f"invalid explicit split in linked group: {sorted(explicit)}")
        if len(explicit) > 1:
            raise DatasetValidationError(f"prompt/image leakage group has conflicting explicit splits: {sorted(explicit)}")
        if explicit:
            selected = explicit.pop()
        else:
            key = "|".join(sorted(rows[index]["id"] for index in indexes))
            value = int(_sha256_text(key)[:12], 16) / float(16**12)
            selected = labels[0] if value < ratios[0] else labels[1] if value < ratios[0] + ratios[1] else labels[2]
        for index in indexes:
            rows[index]["assigned_split"] = selected


def _build_contract(raw: dict[str, Any]) -> tuple[dict[str, Any], dict[str, Any]]:
    import sys

    worker_root = STACK_ROOT / "python-worker"
    if str(worker_root) not in sys.path:
        sys.path.insert(0, str(worker_root))
    from app.design_state import build_design_state
    from app.parametric_generators import build_geometry_contract

    category = raw["category"]
    analysis = raw.get("source_analysis") if isinstance(raw.get("source_analysis"), dict) else {}
    if isinstance(raw.get("dimensions"), dict):
        analysis = {**analysis, "dimensions": raw["dimensions"]}
    state = build_design_state(
        project_id=f"DATASET-{raw['id'].upper()}",
        revision=1,
        prompt=raw["prompt"],
        category=category,
        selected_2d_id=f"DATASET-{raw['id']}",
        source_analysis=analysis,
    )
    design_spec = raw.get("design_spec") if isinstance(raw.get("design_spec"), dict) else state["design_spec"]
    state["design_spec"] = design_spec
    contract = raw.get("geometry_contract") if isinstance(raw.get("geometry_contract"), dict) else build_geometry_contract(
        state, category, MODE_FOR_CATEGORY[category]
    )
    return design_spec, contract


def _normalize_image(source: Path, destination: Path, max_side: int) -> str:
    with Image.open(source) as image:
        prepared = ImageOps.exif_transpose(image).convert("RGB")
        if max(prepared.size) > max_side:
            prepared.thumbnail((max_side, max_side), Image.Resampling.LANCZOS)
        prepared.save(destination, format="PNG", optimize=True)
    return _sha256_bytes(destination.read_bytes())


def preprocess_dataset(
    raw_manifest: str | Path,
    output_dir: str | Path,
    *,
    max_image_side: int = 2048,
    min_images: int = 1,
    split_ratios: tuple[float, float, float] = (0.8, 0.1, 0.1),
    allowlist_path: str | Path | None = None,
) -> dict[str, Any]:
    """Convert external raw records into a validated, leakage-safe training dataset."""
    if max_image_side < 256:
        raise DatasetValidationError("max_image_side must be at least 256")
    raw_path = Path(raw_manifest).expanduser().resolve()
    output = Path(output_dir).expanduser().resolve()
    if output.exists():
        raise DatasetValidationError(f"output directory already exists: {output}")
    allowed, allowlist = _read_allowlist(Path(allowlist_path).expanduser().resolve() if allowlist_path else None)
    rows: list[dict[str, Any]] = []
    ids: set[str] = set()
    for raw in _read_jsonl(raw_path):
        record_id = _slug(str(raw.get("id") or ""), "")
        category = str(raw.get("category") or "")
        prompt = str(raw.get("prompt") or "").strip()
        if not record_id or record_id in ids:
            raise DatasetValidationError(f"line {raw['_line_number']}: id is missing or duplicated")
        if category not in CATEGORIES:
            raise DatasetValidationError(f"line {raw['_line_number']}: unsupported category {category}")
        if not prompt:
            raise DatasetValidationError(f"line {raw['_line_number']}: prompt is required")
        provenance = raw.get("provenance")
        if not isinstance(provenance, dict):
            raise DatasetValidationError(f"line {raw['_line_number']}: provenance is required")
        license_id = str(provenance.get("license") or "")
        if license_id not in allowed or provenance.get("training_allowed") is not True:
            raise DatasetValidationError(f"line {raw['_line_number']}: training license/permission is not allowed")
        ids.add(record_id)
        rows.append({
            **raw,
            "id": record_id,
            "category": category,
            "prompt": prompt,
            "prompt_hash": _sha256_text(prompt),
            "image_entries": _image_entries(raw, raw_path.parent, min_images),
        })
    _assign_splits(rows, split_ratios)

    staging = output.with_name(f"{output.name}.staging-{uuid.uuid4().hex[:8]}")
    images_dir = staging / "images"
    images_dir.mkdir(parents=True)
    records: list[dict[str, Any]] = []
    try:
        for raw in rows:
            design_spec, contract = _build_contract(raw)
            image_paths: list[str] = []
            image_hashes: dict[str, str] = {}
            for index, image in enumerate(raw["image_entries"], start=1):
                view = image["view"]
                if view in image_hashes:
                    view = f"{view}_{index:02d}"
                relative = Path("images") / f"{raw['id']}_{view}.png"
                digest = _normalize_image(image["source"], staging / relative, max_image_side)
                image_paths.append(relative.as_posix())
                image_hashes[view] = digest
            provenance = dict(raw["provenance"])
            provenance.setdefault("source_kind", "external_curated")
            provenance.setdefault("source_id", raw["id"])
            provenance.setdefault("generator_version", str(contract.get("generator_version") or "external"))
            records.append({
                "schema_version": DATASET_SCHEMA,
                "id": raw["id"],
                "category": raw["category"],
                "split": raw["assigned_split"],
                "task": str(raw.get("task") or "multi_view_image_to_design_spec"),
                "prompt": raw["prompt"],
                "images": image_paths,
                "image_sha256": image_hashes,
                "design_spec": design_spec,
                "geometry_contract": contract,
                **({"cad_context": raw["cad_context"]} if isinstance(raw.get("cad_context"), dict) else {}),
                "provenance": provenance,
            })
        (staging / "records.jsonl").write_text(
            "".join(json.dumps(record, ensure_ascii=False, sort_keys=True) + "\n" for record in records),
            encoding="utf-8",
        )
        shutil.copyfile(allowlist, staging / "license_allowlist.json")
        validation = validate_dataset(staging)
        report = {
            "schema": "xconcep.cad-vlm-preprocess-report/1.0",
            "raw_manifest": raw_path.name,
            "raw_manifest_sha256": _sha256_bytes(raw_path.read_bytes()),
            "max_image_side": max_image_side,
            "min_images": min_images,
            "split_ratios": {"train": split_ratios[0], "eval": split_ratios[1], "test": split_ratios[2]},
            "validation": validation,
        }
        (staging / "preprocessing_report.json").write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        staging.replace(output)
        return report
    except Exception:
        if staging.exists():
            shutil.rmtree(staging)
        raise
