param(
    [string]$BaseUrl = "http://127.0.0.1:8080",
    [string]$Prompt = "곡면 안전커버와 인체공학 손잡이를 적용한 소형 산업용 비전 검사 모듈",
    [ValidateSet("hunyuan3d", "openscad", "blender", "hybrid")]
    [string]$EngineOverride = "hunyuan3d"
)

$ErrorActionPreference = "Stop"

function Assert-True([bool]$Condition, [string]$Message) {
    if (-not $Condition) { throw $Message }
}

function Invoke-JsonPost([string]$Uri, [hashtable]$Body) {
    return Invoke-RestMethod -Method Post -Uri $Uri -ContentType "application/json; charset=utf-8" `
        -Body ($Body | ConvertTo-Json -Depth 20) -TimeoutSec 7200
}

$web = Invoke-RestMethod -Uri "$BaseUrl/health" -TimeoutSec 10
Assert-True ($web.status -eq "ok") "Web health check failed"

$status = Invoke-RestMethod -Uri "$BaseUrl/api/system-status" -TimeoutSec 30
$worker = $status.worker
Assert-True ($worker.runtime_ready -eq $true) "Worker is not live-ready: $($worker | ConvertTo-Json -Depth 8 -Compress)"
Assert-True ($worker.image.mode -eq "comfyui") "ComfyUI is not the active 2D provider"
Assert-True ($worker.image.connected -eq $true) "ComfyUI is not connected"
Assert-True ($worker.image_to_3d.provider -eq "triposr") "TripoSR is not the active image-to-3D provider"
Assert-True ($worker.image_to_3d.connected -eq $true) "TripoSR is not connected"

$created = Invoke-JsonPost "$BaseUrl/api/projects" @{
    prompt = $Prompt
    category = "module"
    output_goal = "fast"
    quality_profile = "preview"
}
$project = $created.project
Assert-True ($project.status -eq "2d_ready") "2D project did not complete"
Assert-True ($project.results_2d.Count -eq 4) "Expected four 2D concepts"
$concept = $project.results_2d[0]

$generated = Invoke-JsonPost "$BaseUrl/api/projects/$($project.id)/generate-3d" @{
    selected_2d_id = $concept.id
    output_goal = "fast"
    quality_profile = "preview"
    engine_override = $EngineOverride
}
$project3d = $generated.project
$result = $project3d.result_3d
Assert-True ($project3d.status -eq "completed") "3D project did not complete"
Assert-True ([bool]$result.glb_url) "3D result has no GLB URL"
Assert-True ($result.provider.engine -eq "triposr") "3D result was not generated by TripoSR"

$glb = Invoke-WebRequest -UseBasicParsing -Uri "$BaseUrl$($result.glb_url)" -TimeoutSec 120
$bytes = $glb.Content
if ($bytes -is [string]) { $bytes = [Text.Encoding]::ISO8859_1.GetBytes($bytes) }
Assert-True ($bytes.Length -gt 100000) "Downloaded GLB is unexpectedly small"
$header = [Text.Encoding]::ASCII.GetString($bytes[0..3])
Assert-True ($header -eq "glTF") "Downloaded asset is not a binary GLB"

[ordered]@{
    status = "pass"
    execution_profile = $worker.execution_profile
    project_id = $project.id
    concepts = $project.results_2d.Count
    image_provider = $worker.image.mode
    image_model = $worker.image.model
    shape_provider = $result.provider.engine
    glb_bytes = $bytes.Length
    validation_grade = $result.validation_grade
    glb_url = $result.glb_url
} | ConvertTo-Json -Depth 6
