<?php
declare(strict_types=1);

namespace CadAi;

final class ArtifactWriter
{
    public static function writeJson(string $path, array $data): void
    {
        self::ensureParent($path);
        $json = json_encode($data, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT);
        if ($json === false || file_put_contents($path, $json . PHP_EOL, LOCK_EX) === false) {
            throw new \RuntimeException("JSON 저장 실패: {$path}");
        }
    }

    public static function writeText(string $path, string $content): void
    {
        self::ensureParent($path);
        if (file_put_contents($path, $content, LOCK_EX) === false) {
            throw new \RuntimeException("파일 저장 실패: {$path}");
        }
    }

    public static function baselineVector(array $geometry): array
    {
        $counts = $geometry['entity_counts'] ?? [];
        $bbox = $geometry['bbox']['extent'] ?? [0.0, 0.0, 0.0];
        $topology = $geometry['topology'] ?? [];
        $surfaces = $geometry['surfaces'] ?? [];
        return array_map('floatval', [
            array_sum($counts),
            count($counts),
            count($geometry['layers'] ?? []),
            count($geometry['products'] ?? []),
            count($geometry['texts'] ?? []),
            count($geometry['points'] ?? []),
            $bbox[0] ?? 0,
            $bbox[1] ?? 0,
            $bbox[2] ?? 0,
            $topology['edge_count'] ?? 0,
            $topology['face_count'] ?? 0,
            $topology['shell_count'] ?? 0,
            $topology['solid_count'] ?? 0,
            array_sum($surfaces),
        ]);
    }

    public static function svg(array $geometry): string
    {
        $width = 900;
        $height = 600;
        $padding = 45;
        $bbox = $geometry['bbox'] ?? null;
        $min = $bbox['min'] ?? [0, 0, 0];
        $extent = $bbox['extent'] ?? [1, 1, 0];
        $sx = ($width - $padding * 2) / max(abs((float)($extent[0] ?? 0)), 1.0);
        $sy = ($height - $padding * 2) / max(abs((float)($extent[1] ?? 0)), 1.0);
        $scale = min($sx, $sy);
        $map = static function (array $point) use ($min, $height, $padding, $scale): array {
            return [
                $padding + ((float)$point[0] - (float)$min[0]) * $scale,
                $height - $padding - ((float)$point[1] - (float)$min[1]) * $scale,
            ];
        };
        $shapes = [];
        foreach ($geometry['primitives'] ?? [] as $primitive) {
            if (($primitive['type'] ?? '') === 'line') {
                [$x1, $y1] = $map($primitive['start']);
                [$x2, $y2] = $map($primitive['end']);
                $shapes[] = sprintf(
                    '<line x1="%.2f" y1="%.2f" x2="%.2f" y2="%.2f" />',
                    $x1, $y1, $x2, $y2
                );
            } elseif (($primitive['type'] ?? '') === 'circle') {
                [$cx, $cy] = $map($primitive['center']);
                $r = abs((float)$primitive['radius']) * $scale;
                $shapes[] = sprintf('<circle cx="%.2f" cy="%.2f" r="%.2f" />', $cx, $cy, $r);
            }
        }
        if ($shapes === []) {
            $points = $geometry['points'] ?? [];
            for ($i = 1, $count = count($points); $i < $count; $i++) {
                [$x1, $y1] = $map($points[$i - 1]);
                [$x2, $y2] = $map($points[$i]);
                $shapes[] = sprintf(
                    '<line x1="%.2f" y1="%.2f" x2="%.2f" y2="%.2f" />',
                    $x1, $y1, $x2, $y2
                );
            }
        }
        $body = implode(PHP_EOL, $shapes);
        return <<<SVG
<svg xmlns="http://www.w3.org/2000/svg" width="{$width}" height="{$height}" viewBox="0 0 {$width} {$height}">
  <rect width="100%" height="100%" fill="#071626"/>
  <g fill="none" stroke="#38d4ff" stroke-width="3" stroke-linecap="round" stroke-linejoin="round">
    {$body}
  </g>
  <text x="28" y="38" fill="#a8bacb" font-family="sans-serif" font-size="18">CAD AI normalized preview</text>
</svg>
SVG;
    }

    public static function ply(array $geometry, int $target = 256): string
    {
        $points = $geometry['points'] ?? [];
        if ($points === []) {
            $bbox = $geometry['bbox'];
            if (is_array($bbox)) {
                $points = [$bbox['min'], $bbox['max']];
            } else {
                $points = [[0.0, 0.0, 0.0]];
            }
        }
        $expanded = [];
        for ($i = 0; $i < $target; $i++) {
            $expanded[] = $points[$i % count($points)];
        }
        $lines = [
            'ply', 'format ascii 1.0', 'comment generated by CAD AI PHP',
            'element vertex ' . count($expanded),
            'property float x', 'property float y', 'property float z', 'end_header',
        ];
        foreach ($expanded as $point) {
            $lines[] = sprintf(
                '%.8F %.8F %.8F',
                (float)($point[0] ?? 0),
                (float)($point[1] ?? 0),
                (float)($point[2] ?? 0)
            );
        }
        return implode(PHP_EOL, $lines) . PHP_EOL;
    }

    private static function ensureParent(string $path): void
    {
        $parent = dirname($path);
        if (!is_dir($parent) && !mkdir($parent, 0770, true) && !is_dir($parent)) {
            throw new \RuntimeException("디렉터리 생성 실패: {$parent}");
        }
    }
}
